"""
pgvector-based vector store using Ollama for local embeddings.
No external API — embeddings are generated by the local Ollama instance.

Three logical "collections" as PostgreSQL tables:
  - learning_resources   → LearningResource model
  - generated_content    → GeneratedContent model
  - user_knowledge       → UserKnowledge model

Default model: nomic-embed-text (768 dims)
"""

from ollama import AsyncClient
from app.config import settings

_client = AsyncClient(host=settings.OLLAMA_BASE_URL)


async def embed(text: str) -> list[float]:
    """Return an embedding vector for the given text using Ollama."""
    response = await _client.embeddings(
        model=settings.OLLAMA_EMBED_MODEL,
        prompt=text[:4000],  # safety trim
    )
    return response.embedding
